# Generated by Django 4.2.5 on 2024-03-14 11:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("metro", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Название проекта"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Слаг")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="p/p/i", verbose_name="Изображение"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Примечание")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Business", "Бизнес"),
                            ("DeLuxe", "Делюкс"),
                            ("Comfort", "Комфорт"),
                            ("Comfort+", "Комфорт+"),
                        ],
                        default="Comfort",
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "time_to_station",
                    models.PositiveSmallIntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="Время до метро",
                    ),
                ),
                (
                    "metro_station",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="metro.metrostation",
                        verbose_name="Станция метро",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
    ]
