# Generated by Django 4.2.5 on 2024-03-21 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAdvantagesBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Заголовок")),
            ],
            options={
                "verbose_name": "Блок преимуществ",
                "verbose_name_plural": "Блок преимуществ",
            },
        ),
        migrations.CreateModel(
            name="ProjectAdvantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Подряд")),
                ("title", models.CharField(max_length=50, verbose_name="Заголовок")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="p/pab/i", verbose_name="Изображение"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "advantages_block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_advantages",
                        to="projects.projectadvantagesblock",
                        verbose_name="Блок преимуществ",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_advantages",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преимущество проекта",
                "verbose_name_plural": "Преимущества проекта",
                "ordering": ("order",),
                "abstract": False,
            },
        ),
    ]
