# Generated by Django 4.2.5 on 2024-03-25 10:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MortgageBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Название банка"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Слаг")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="m/mb/l", verbose_name="Логотип"
                    ),
                ),
            ],
            options={
                "verbose_name": "Банк",
                "verbose_name_plural": "Банки",
            },
        ),
        migrations.CreateModel(
            name="MortgageOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("min_sum", models.PositiveIntegerField(verbose_name="Минимальная сумма кредита")),
                ("max_sum", models.PositiveIntegerField(verbose_name="Максимальная сумма кредита")),
                (
                    "min_term",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="Минимальный срок",
                    ),
                ),
                (
                    "max_term",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="Максимальный срок",
                    ),
                ),
                ("rate", models.PositiveSmallIntegerField(default=0, verbose_name="Ставка")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Standart", "Стандартный"),
                            ("Families", "Семейная"),
                            ("Army", "Военная"),
                            ("Government", "Государственная"),
                        ],
                        default="Standart",
                        max_length=50,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mortgage_offers",
                        to="mortgage.mortgagebank",
                        verbose_name="Предложение банка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предложение",
                "verbose_name_plural": "Предложения",
            },
        ),
    ]
