# Generated by Django 4.2.5 on 2024-03-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_apartment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="price_per_meter",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="Цена за квадратный метр"
            ),
        ),
    ]
