from .about_company_serializer import AboutCompanySerializer
from .about_company_card_serializer import AboutCompanyCardSerializer
from .about_company_team_slide_serializer import AboutCompanyTeamSlideSerializer
