# Generated by Django 4.2.5 on 2024-03-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mainpagetopslide",
            options={
                "ordering": ("order",),
                "verbose_name": "Верхний слайд",
                "verbose_name_plural": "Верхние слайды",
            },
        ),
        migrations.AddField(
            model_name="mainpagetopslide",
            name="order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="порядок"),
        ),
    ]
