# Generated by Django 4.2.5 on 2024-03-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0002_alter_mainpagetopslide_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApartmentSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        choices=[
                            ("Business", "Квартиры бизнесс-класса"),
                            ("Near River", "Апартаменты у реки"),
                            ("Apartments with view", "Апартаменты с видами"),
                        ],
                        default="Business",
                        max_length=50,
                        verbose_name="Название катеогории",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="as/as/i", verbose_name="Изображение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Подборка квартир",
                "verbose_name_plural": "Подборки квартир",
            },
        ),
    ]
