# Generated by Django 4.2.5 on 2024-03-18 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0003_apartmentselection"),
    ]

    operations = [
        migrations.CreateModel(
            name="RulesBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Заголовок")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="mp/rb/i", verbose_name="Изображение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок правил",
                "verbose_name_plural": "Блок правил",
            },
        ),
        migrations.CreateModel(
            name="RulesSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Подряд")),
                ("title", models.CharField(max_length=50, verbose_name="Заголовок")),
                (
                    "short_description",
                    models.TextField(blank=True, max_length=150, verbose_name="Короткое описание"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules_slides",
                        to="main_page.rulesblock",
                        verbose_name="Блок правил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слайд",
                "verbose_name_plural": "Слайды",
                "abstract": False,
            },
        ),
    ]
