# Generated by Django 4.2.5 on 2024-03-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_rulesslide_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagetopslide',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Подряд'),
        ),
    ]
