# Generated by Django 4.2.5 on 2024-03-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Заголовок")),
                (
                    "head_description",
                    models.CharField(max_length=50, verbose_name="Верхнее описание"),
                ),
                (
                    "low_description",
                    models.CharField(max_length=50, verbose_name="Нижнее описание"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="ac/ac/i", verbose_name="Изображение"
                    ),
                ),
            ],
            options={
                "verbose_name": "О компании",
                "verbose_name_plural": "О компании",
            },
        ),
        migrations.CreateModel(
            name="AboutCompanyCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("head_title", models.CharField(max_length=50, verbose_name="Верхний заголовок")),
                ("body_title", models.CharField(max_length=50, verbose_name="Нижний заголовок")),
            ],
            options={
                "verbose_name": "Карточка",
                "verbose_name_plural": "Карточки",
            },
        ),
        migrations.CreateModel(
            name="AboutCompanyTeamSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Подряд")),
                (
                    "big_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ac/act/bi",
                        verbose_name="Большое изображение",
                    ),
                ),
                (
                    "small_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ac/act/si",
                        verbose_name="Маленькое изображение",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ac/act/bi",
                        verbose_name="Фоновое изображение",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="Год")),
                ("full_name", models.CharField(max_length=30, verbose_name="Фамилия, Имя")),
                ("description", models.CharField(max_length=50, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Слайд",
                "verbose_name_plural": "Слайды",
                "ordering": ("order",),
                "abstract": False,
            },
        ),
    ]
